spring:
  application:
    name: order-service-rest
  # redis缓存
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 1024 # default 8
        max-wait: 10000 # default -1 不阻塞
        max-idle: 200 # default 8
        min-idle: 5 # default 0
  cloud:
    sentinel:
      # 客户端配置sentinel的transport模块
      transport:
        port: 8719
        dashboard: localhost:8080
      # sentinel动态规则扩展
      datasource:
        ds1:
          file:
            file: classpath:flowRule.json
            dataType: json
            ruleType: FLOW
  # zipkin配置
  zipkin:
    base-url: http://localhost:9411/ # zipkin服务端地址
    sender:
      type: WEB # 数据传输方式，web表示http报文
  sleuth:
    sampler:
      probability: 1.0 # 数据收集百分比，默认0.1
server:
  port: 9090
  tomcat:
    max-threads: 10 # 降低最大并发线程来模拟高并发
eureka:
  instance:
    hostname: order-service-rest
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        # actuator开启节点
        include: hystrix.stream
hystrix:
  dashboard:
    # dashboard允许访问
    proxy-stream-allow-list: "localhost"